#!/usr/bin/env bash
# Deploy the stellar-invoice contract to Stellar Testnet.
#
# Requirements:
#   - rustup target add wasm32-unknown-unknown
#   - stellar CLI installed (`cargo install --locked stellar-cli`)
#
# Usage:
#   ./scripts/deploy-testnet.sh [account-name]
#
# If no account name is given, "deployer" is used.
# The script:
#   1. Creates and funds a testnet account if needed
#   2. Builds the WASM
#   3. Deploys to testnet
#   4. Writes the contract ID to .env.testnet

set -euo pipefail

ACCOUNT_NAME="${1:-deployer}"
NETWORK="testnet"
CONTRACT_NAME="stellar-invoice"
WASM_PATH="target/wasm32-unknown-unknown/release/stellar_invoice.wasm"
ENV_FILE=".env.testnet"

echo "==> Using account: $ACCOUNT_NAME on $NETWORK"

# 1. Add testnet network configuration if missing
stellar network add testnet \
  --rpc-url https://soroban-testnet.stellar.org \
  --network-passphrase "Test SDF Network ; September 2015" \
  2>/dev/null || true

# 2. Generate account if missing, fund it
if ! stellar keys ls 2>/dev/null | grep -q "^$ACCOUNT_NAME$"; then
  echo "==> Generating new account: $ACCOUNT_NAME"
  stellar keys generate "$ACCOUNT_NAME" --network "$NETWORK"
fi
echo "==> Funding $ACCOUNT_NAME on testnet (no-op if already funded)"
stellar keys fund "$ACCOUNT_NAME" --network "$NETWORK" || true
DEPLOYER_ADDR="$(stellar keys address "$ACCOUNT_NAME")"
echo "==> Deployer address: $DEPLOYER_ADDR"

# 3. Build the contract
echo "==> Building WASM"
rustup target add wasm32-unknown-unknown >/dev/null 2>&1 || true
stellar contract build

# 4. Deploy to testnet
echo "==> Deploying $CONTRACT_NAME"
CONTRACT_ID="$(
  stellar contract deploy \
    --wasm "$WASM_PATH" \
    --source "$ACCOUNT_NAME" \
    --network "$NETWORK"
)"

echo ""
echo "================================================================"
echo "  ✅ Deployed contract:"
echo "  CONTRACT_ID=$CONTRACT_ID"
echo "  DEPLOYER_ADDRESS=$DEPLOYER_ADDR"
echo "  Explorer: https://stellar.expert/explorer/testnet/contract/$CONTRACT_ID"
echo "================================================================"

# 5. Write env file
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/deploy-testnet.sh
NEXT_PUBLIC_STELLAR_NETWORK=TESTNET
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
NEXT_PUBLIC_STELLAR_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
NEXT_PUBLIC_INVOICE_CONTRACT_ID=$CONTRACT_ID
NEXT_PUBLIC_X402_SERVER_URL=http://localhost:4000

# x402 server side
STELLAR_NETWORK=testnet
INVOICE_CONTRACT_ID=$CONTRACT_ID
DEPLOYER_ACCOUNT=$ACCOUNT_NAME
DEPLOYER_ADDRESS=$DEPLOYER_ADDR
USDC_ISSUER=GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5
FRONTEND_URL=http://localhost:3000
PORT=4000
EOF

echo ""
echo "==> Wrote $ENV_FILE"
echo "    Copy values into your local .env to use the deployed contract."
